
services:
  app:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: flowchart_app
    ports:
      - "8000:8000"
    environment:
      - DJANGO_SETTINGS_MODULE=projectname.settings
    volumes:
      - ./backend:/app
    depends_on:
      - db

  db:
    image: postgres:13
    container_name: flowchart_db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: flowchart_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
